apiVersion: v1
kind: Pod
metadata:
  name: neuropixel-jupyter-gpu
  labels:
    app: neuropixel-jupyter-gpu # Reference this in your service
spec:
  restartPolicy: OnFailure
  hostNetwork: true
  volumes:
    - name: mnt
      hostPath:
        path: /mnt
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - at-gpu7
  priorityClassName: medium-priority #high-priority
  tolerations:
    - key: "gpu"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  containers:
    - name: neuropixel-jupyter-gpu
      image: at-docker.ad.bcm.edu:5000/kilosort4:latest
      imagePullPolicy: Always # needed because the image tag is not latest
      volumeMounts:
        - name: mnt
          mountPath: /mnt
      resources:
        requests:
          cpu: "1"
          memory: "30Gi"
        limits:
          nvidia.com/gpu: "1"
      env:
        - name: DJ_HOST
          valueFrom:
            secretKeyRef:
              name: datajoint-credentials
              key: DJ_HOST
        - name: DJ_USER
          valueFrom:
            secretKeyRef:
              name: datajoint-credentials
              key: DJ_USER
        - name: DJ_PASS
          valueFrom:
            secretKeyRef:
              name: datajoint-credentials
              key: DJ_PASS
      command: ["/bin/bash"]
      args: ["-c",
        "mkdir -p /src &&\
        cd /src &&\
        git clone https://github.com/Cpapa97/neuropixel-pipeline.git &&\
        cd neuropixel-pipeline &&\
        git switch data-interface; \
        conda run --no-capture-output -n kilosort &&\
        pip3 install . &&\
        cd notebooks &&\
        jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser --NotebookApp.token=''"]

---
kind: Service
apiVersion: v1
metadata:
  name: neuropixel-jupyter-gpu-service
spec:
  type: NodePort
  selector:
    app: neuropixel-jupyter-gpu # reference the app label from the top
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    nodePort: 31999